import { test, expect } from '@playwright/test';

test('Guide covers startup, keyboard and phone controls, connections and layout in desktop and fullscreen', async ({ page }) => {
  await page.goto('/'); await expect(page.locator('#connection-status')).toContainText('Keyboard');
  const guide = page.getByRole('button', { name: 'Guide', exact: true });
  await guide.click(); await expect(page.getByRole('dialog', { name: 'Guide', exact: true })).toBeVisible();
  await expect(page.getByRole('tabpanel', { name: 'Startup', exact: true })).toContainText('Your first flight');
  await page.getByRole('tab', { name: 'Controls', exact: true }).click();
  await expect(page.getByRole('tabpanel', { name: 'Controls', exact: true })).toContainText('Left stick up / down');
  await page.getByRole('tab', { name: 'Controls', exact: true }).press('ArrowRight');
  await expect(page.getByRole('tab', { name: 'Connection', exact: true })).toBeFocused();
  await expect(page.getByRole('tabpanel', { name: 'Connection', exact: true })).toContainText('Local Android USB');
  await page.getByRole('button', { name: 'Open pairing' }).click();
  await expect(page.locator('#guide-dialog')).not.toBeVisible(); await expect(page.locator('#pair-dialog')).toBeVisible();
  await page.getByRole('button', { name: 'Close pairing' }).click();
  await page.locator('#takeoff').click(); await expect(page.locator('#flight-status')).toHaveAttribute('data-mode', 'flying', { timeout: 10_000 });
  await guide.click(); await expect(page.locator('#flight-status')).toHaveAttribute('data-paused', 'true');
  const altitude = await page.locator('#altitude').innerText();
  await page.keyboard.press('w'); await page.keyboard.press('t');
  await expect(page.locator('#altitude')).toHaveText(altitude);
  await page.getByRole('tab', { name: 'Layout', exact: true }).click();
  await expect(page.getByRole('tabpanel', { name: 'Layout', exact: true })).toContainText('Shift-drag');
  await page.screenshot({ path: 'test-results/guide-desktop.png' });
  await page.keyboard.press('Escape'); await expect(page.locator('#guide-dialog')).not.toBeVisible(); await expect(guide).toBeFocused();
  await page.locator('#simulator-fullscreen').click(); await expect(guide).toBeVisible();
  await page.setViewportSize({ width: 320, height: 568 });
  await guide.click(); await page.getByRole('tab', { name: 'Startup', exact: true }).click();
  await expect(page.locator('#guide-startup')).toBeVisible();
  expect(await page.locator('#guide-dialog').evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/guide-mobile.png' });
  await page.keyboard.press('Escape'); await expect(page.locator('#guide-dialog')).not.toBeVisible();
  await expect(page.locator('.simulator')).toHaveClass(/is-fullscreen/);
  await page.locator('#simulator-fullscreen').click(); await expect(guide).toBeVisible();
});

test('drone presets, custom values, validation and cancel work and saved tuning affects flight', async ({ page }) => {
  test.setTimeout(60_000);
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/'); await expect(page.locator('#connection-status')).toContainText('Keyboard');
  const setup = page.getByRole('button', { name: 'Drone parameters', exact: true });
  await setup.click(); await page.getByLabel('Drone preset', { exact: true }).selectOption('mini-4-pro');
  await expect(page.getByLabel('Horizontal speed', { exact: true })).toHaveValue('16');
  await expect(page.getByRole('link', { name: 'Manufacturer specifications' })).toHaveAttribute('href', 'https://www.dji.com/mini-4-pro/specs');
  await page.getByRole('button', { name: 'Cancel', exact: true }).click();
  await expect(page.locator('#flight-speed')).toHaveValue('20');
  await setup.click(); await expect(page.getByLabel('Drone preset', { exact: true })).toHaveValue('generic');
  await page.getByLabel('Drone preset', { exact: true }).selectOption('mavic-3-classic');
  await expect(page.getByLabel('Climb speed', { exact: true })).toHaveValue('8');
  await expect(page.getByLabel('Descent speed', { exact: true })).toHaveValue('6');
  await page.getByLabel('Drone preset', { exact: true }).selectOption('air-3');
  await page.getByRole('button', { name: 'Apply settings' }).click(); await expect(page.locator('#flight-speed')).toHaveValue('21');
  await page.reload(); await expect(page.locator('#flight-speed')).toHaveValue('21');
  await page.locator('#flight-speed').selectOption('5');
  await setup.click(); await expect(page.getByLabel('Drone preset', { exact: true })).toHaveValue('air-3');
  await expect(page.getByLabel('Horizontal speed', { exact: true })).toHaveValue('21');
  await page.getByLabel('Horizontal speed', { exact: true }).fill('0');
  await page.getByRole('button', { name: 'Apply settings' }).click(); await expect(page.locator('#drone-dialog')).toBeVisible();
  await page.getByLabel('Horizontal speed', { exact: true }).fill('2');
  await page.getByLabel('Climb speed', { exact: true }).fill('1');
  await page.getByLabel('Descent speed', { exact: true }).fill('0.5');
  await page.getByLabel('Turn speed', { exact: true }).fill('45');
  await page.getByLabel('Camera field of view', { exact: true }).fill('80');
  await expect(page.getByLabel('Drone preset', { exact: true })).toHaveValue('custom');
  await page.screenshot({ path: 'test-results/drone-parameters-desktop.png' });
  await page.getByRole('button', { name: 'Apply settings' }).click();
  await expect(page.locator('#flight-speed')).toHaveValue('2');
  await expect(page.locator('.camera-spec')).toHaveAttribute('aria-label', /80° vertical/);
  await expect(page.locator('#flight-status')).toHaveAttribute('data-paused', 'true');
  await page.locator('#takeoff').click(); await expect(page.locator('#flight-status')).toHaveAttribute('data-mode', 'flying', { timeout: 10_000 });
  await page.locator('#stage').focus();
  await page.keyboard.down('ArrowRight'); await expect.poll(async () => parseFloat(await page.locator('#speed').innerText())).toBe(2); await page.keyboard.up('ArrowRight');
  await setup.click(); await expect(page.locator('#flight-status')).toHaveAttribute('data-paused', 'true');
  await page.getByRole('button', { name: 'Close drone parameters' }).click();
  await page.reload(); await expect(page.locator('#flight-speed')).toHaveValue('2');
  await setup.click(); await expect(page.getByLabel('Turn speed', { exact: true })).toHaveValue('45');
  await page.getByRole('button', { name: 'Restore trainer defaults' }).click();
  await page.getByRole('button', { name: 'Apply settings' }).click(); await expect(page.locator('#flight-speed')).toHaveValue('20');
  await page.locator('#simulator-fullscreen').click(); await expect(setup).toBeVisible();
  await page.setViewportSize({ width: 320, height: 568 }); await setup.click();
  await page.getByLabel('Drone preset', { exact: true }).selectOption('mini-4-pro');
  await page.getByRole('button', { name: 'Apply settings' }).scrollIntoViewIfNeeded();
  expect(await page.locator('#drone-dialog').evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/drone-parameters-mobile.png' });
  await page.getByRole('button', { name: 'Apply settings' }).click(); await page.locator('#simulator-fullscreen').click();
  await expect(page.locator('#flight-speed')).toHaveValue('16'); expect(errors).toEqual([]);
});

test('fixed observer can orbit, pan and zoom, keeps its viewpoint through other cameras, and resets', async ({ page }) => {
  await page.goto('/'); await expect(page.locator('#connection-status')).toContainText('Keyboard');
  const view = page.locator('#observer-view'), mode = page.locator('#observer-mode');
  const image = () => view.screenshot({ animations: 'disabled', style: '#fixed-view-hint, .view-heading { visibility: hidden; } .observer-view { outline: none !important; }' });
  await page.mouse.move(0, 0);
  const initial = await image(), rect = (await view.boundingBox())!;
  const drag = async (dx: number, dy: number) => {
    await page.mouse.move(rect.x + rect.width * .45, rect.y + rect.height * .4); await page.mouse.down();
    await page.mouse.move(rect.x + rect.width * .45 + dx, rect.y + rect.height * .4 + dy, { steps: 8 }); await page.mouse.up(); await page.mouse.move(0, 0);
  };
  await drag(90, 25); const orbited = await image(); expect(orbited.equals(initial)).toBe(false);
  await page.keyboard.down('Shift'); await drag(40, 0); await page.keyboard.up('Shift');
  const panned = await image(); expect(panned.equals(orbited)).toBe(false);
  await page.mouse.move(rect.x + rect.width / 2, rect.y + rect.height * .4); await page.mouse.wheel(0, -250); await page.mouse.move(0, 0);
  const zoomed = await image(); expect(zoomed.equals(panned)).toBe(false);
  await mode.selectOption('follow'); await expect(page.locator('#observer-reset')).toBeHidden();
  await mode.selectOption('overview'); await mode.selectOption('fixed'); await page.mouse.move(0, 0);
  expect((await image()).equals(zoomed)).toBe(true);
  await view.focus(); await page.keyboard.press('Alt+ArrowLeft'); const keyboardPan = await image(); expect(keyboardPan.equals(zoomed)).toBe(false);
  await page.keyboard.press('Alt+Equal'); expect((await image()).equals(keyboardPan)).toBe(false);
  await page.locator('#observer-reset').click(); await page.mouse.move(0, 0); expect((await image()).equals(initial)).toBe(true);
  await page.locator('#takeoff').click(); await expect(page.locator('#flight-status')).toHaveAttribute('data-mode', 'flying', { timeout: 10_000 });
  await view.focus(); await page.keyboard.down('ArrowRight');
  await expect.poll(async () => parseFloat(await page.locator('#speed').innerText())).toBeGreaterThan(0); await page.keyboard.up('ArrowRight');
});
