import { test, expect } from '@playwright/test';

test('Silverstone renders the F1 car, tracks airborne laps, freezes, captures and resets across layouts', async ({ page }) => {
  test.setTimeout(60_000);
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/'); await expect(page.locator('#connection-status')).toContainText('Keyboard');
  await page.locator('#map').selectOption('silverstone');
  await expect(page.locator('.world-canvas')).toHaveAttribute('aria-label', 'Silverstone · Formula One rendered from the observer and drone cameras');
  await expect(page.locator('#course-name')).toHaveText('Formula One tracking');
  await expect(page.locator('#course-count')).toContainText(/Lap 1 · \d+ km\/h/);
  await expect(page.locator('#map-tip')).toHaveAttribute('aria-description', /300 m ceiling/);
  await expect(page.locator('#silverstone-credit')).toBeVisible();
  await expect(page.locator('#map-credit')).toBeHidden();
  await page.locator('#takeoff').click();
  await expect(page.locator('#flight-status')).toHaveAttribute('data-mode', 'flying', { timeout: 10_000 });
  await page.locator('#capture').click(); await expect(page.locator('#photos img')).toHaveCount(1);
  await expect(page.locator('#camera-view')).not.toHaveClass(/flash/);
  await page.locator('#pause').click();
  await expect(page.locator('#flight-status')).toHaveAttribute('data-paused', 'true');
  await expect(page.locator('#course-next')).toContainText('In frame');
  const stats = await page.locator('#course-progress').innerText();
  const frozen = await page.locator('#camera-view').screenshot({ path: 'test-results/silverstone-camera.png' });
  expect(await page.locator('#camera-view').screenshot()).toEqual(frozen);
  expect(await page.locator('#course-progress').innerText()).toBe(stats);
  await page.locator('#observer-mode').selectOption('overview');
  await page.screenshot({ path: 'test-results/silverstone-overview.png', fullPage: true, style: '#toast { visibility: hidden; }' });
  await page.locator('#pause').click();
  await expect.poll(() => page.locator('#course-progress').innerText()).not.toBe(stats);
  await page.locator('#reset').click();
  await expect(page.locator('#course-next')).toHaveText('Take off to start · Keep the car in frame');
  await expect(page.locator('#course-count')).toContainText('Lap 1');
  await expect(page.locator('#flight-status')).toHaveAttribute('data-mode', 'grounded');
  await page.getByRole('button', { name: 'Camera only', exact: true }).click();
  await expect(page.locator('#course-progress')).toBeVisible();
  await page.getByRole('button', { name: 'Side by side', exact: true }).click();
  await page.locator('#simulator-fullscreen').click();
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.locator('#course-progress')).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
  await page.screenshot({ path: 'test-results/silverstone-mobile.png', style: '#toast { visibility: hidden; }' });
  await page.locator('#simulator-fullscreen').click();
  await page.locator('#map').selectOption('park');
  await expect(page.locator('#course-progress')).toBeHidden();
  await expect(page.locator('#silverstone-credit')).toBeHidden();
  await page.locator('#map').selectOption('silverstone');
  await expect(page.locator('#course-next')).toHaveText('Take off to start · Keep the car in frame');
  await expect(page.locator('#photos img')).toHaveCount(1);
  expect(errors).toEqual([]);
});
